# Generated by Django 4.2.6 on 2023-10-21 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime', '0002_crimelocation_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crimelocation',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
